### ISSUE TITLE
Veranderen volgorde deployen

### ISSUE THREAD

**Issue by jaelkwakkel** [Windesheim-HBO-ICT/security_workshops#11]
**Workshop naam**: Deployen
### Fout/verbetering
De volgorde waarin de opdrachten worden uitgevoerd zorgt ervoor dat er wordt aangegeven dat aan het eind van opdracht 4 GIT wordt verwacht dat de applicatie draait, terwijl deze het pas doet na opdracht 5 reverse proxy. Of opdracht 4 en 5 omdraaien, of de opdrachten aanpassen zodat het resultaat dat vermeldt staat ook het daadwerkelijke resultaat is.

**Comment by FemkeSpanner** [comment]
verwerkt

**Comment by FemkeSpanner** [comment]
verwerkt! 👍
