### ISSUE TITLE
[Incorrect information]: ZAP request onderscheppen werkt niet of is niet duidelijk

### ISSUE THREAD

**Issue by Labhatorian** [Windesheim-HBO-ICT/security_workshops#21]
### Workshop

ZAP

### Steps

1. Voer opdracht uit met Firefox
2. Zet breakpoint aan
3. Probeer in te loggen met fout wachtwoord

### actual

Website loopt vast en er staat niet in de geschiedenis van de HUD hoe en wat. In ZAP zelf lijkt het van vorige opdrachten nog te staan.

### Expected

Ik denk dat je in de history een request dan hoort te zien zodat het aangepast kan worden. Kon dit niet laten zien in de Workshop toen ik het gaf. In eerste instantie werkte de HUD eerst ook niet en werkte het weer na een restart

**Comment by jaelkwakkel** [comment]
Maakt deze gewijzigde instructie het duidelijker? Het is inderdaad de bedoeling dat de HUD het niet doet, deze is in stap 1 uitgezet.
