### ISSUE TITLE
Duplicate object key error bij opdrach 6 stap 7

### ISSUE THREAD

**Issue by martijnschuman** [Windesheim-HBO-ICT/security_workshops#23]
### Workshop

Risk & Mitigation 1

### Steps

Kopieer de code die staat bij stap 7 en plak het in de Body.

### Actual

![image](https://github.com/Windesheim-HBO-ICT/security_workshops/assets/31829786/b604e195-65bb-4c32-b130-0aff85dcfe0d)

### Expected

`"BasketId":1` moet weg uit de code bij stap 6
![image](https://github.com/Windesheim-HBO-ICT/security_workshops/assets/31829786/de54a779-ebfd-4539-a9c7-74c1723ed8e2)

![image](https://github.com/Windesheim-HBO-ICT/security_workshops/assets/31829786/b7b3814f-7e53-4bbb-ba03-88462a5c975e)

**Comment by jaelkwakkel** [comment]
Het is de bedoeling dat het BasketId dubbel in de body staat. Dit houdt de server voor de gek en maakt het mogelijk om een item in de basket van iemand anders te stoppen.
