### ISSUE TITLE
[Problem]: onduidelijk positie van SQL query

### ISSUE THREAD

**Issue by Jaspervv** [Windesheim-HBO-ICT/security_workshops#24]
### Workshop

Risk & Mitigation 2

### Steps

Opdracht 8 stap 3

### Problem

De stap luidt:
> De Juice Shop geeft nu een error terug met een SQL query.

De bedoeling is dat je je network tab open hebt en vervolgens de Response body van de POST request doorzoekt voor de SQL query. Ik denk dat dit duidelijker genoemd kan worden.

![image](https://github.com/Windesheim-HBO-ICT/security_workshops/assets/35364310/f526d07a-56df-45e4-9565-ae04bb77187d)

**Comment by jaelkwakkel** [comment]
Closed as in #27
