### ISSUE TITLE
Opdracht 13 & 14 werken niet met de eerste docker startup commando

### ISSUE THREAD

**Issue by martijnschuman** [Windesheim-HBO-ICT/security_workshops#26]
### Workshop

Risk & Mitigation 3

### Problem

Opdracht 13 & 14 & 15 kan je niet uitvoeren met deze startup commando `docker run --rm -p 3000:3000 bkimminich/juice-shop`. Je moet hem opstarten met `docker run --rm --env NODE_ENV=unsafe -p 3000:3000 bkimminich/juice-shop`. Misschien handig om dit bij deze opdrachten nog een keer te benoemen

**Comment by Jaspervv** [comment]
dit is ook nodig voor opdracht 15

**Comment by jaelkwakkel** [comment]
Wordt nu bij de opdrachten aangegeven. ( Commit e93b1c095e8dcaeaf9c59a51c99687498acbbfba )
