### ISSUE TITLE
[Incorrect information]: Opdracht 8 SQL-error wordt niet getoond

### ISSUE THREAD

**Issue by jaelkwakkel** [Windesheim-HBO-ICT/security_workshops#27]
### Workshop

Risk & Mitigation 2

### Steps

Opdracht 8

### Actual

Op je scherm bij het inloggen wordt [Object Object] getoond. Vanuit de opdracht is dit waar verwacht wordt de sql-query te zien.

### Expected

De SQL-query is te vinden in de response in het network-tab van dev-tools.

**Comment by Jaspervv** [comment]
hetzelfde probleem als #24

**Comment by jaelkwakkel** [comment]
Klopt, met deze dus ook closes #24
