### ISSUE TITLE
Skylab vertalingen

### ISSUE THREAD

**Issue by martijnschuman** [Windesheim-HBO-ICT/security_workshops#40]
### Workshop

Setup Skylab

### Enhancement

Bij sommige mensen staat Skylab in het nederlands en kan het verwarrend zijn dat in de workshop termin in het engels zijn

**Comment by babelsk** [comment]
Hoi, 

De taal in de interface van Skylab is afhankelijk van de ingestelde taal van de gebruikte browser. Er is geen optie om binnen Skylab de taal separaat aan te passen. Denk dat het snelste is om in de opdrachten zowel de Engelse als Nederlandse termen te gebruiken.

Derk Babeliowsky
Skylab Functioneel Beheer
