### ISSUE TITLE
Toevoegen resultaat command

### ISSUE THREAD

**Issue by YannickBR** [Windesheim-HBO-ICT/security_workshops#8]
**Workshop naam**: Deployeb
### Fout/verbetering
In dit commando

> echo \ "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \ $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \ sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

komt er dit uit

`deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian <releasename> stable`

idee om dit toe te voegen?

**Comment by FemkeSpanner** [comment]
Verwerkt! 👍
